##
## Vergesst nicht den Host-Docker-Socket in die Container zu einzubinden (https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)
## In der Runner-Config:
##     volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
##
image: docker:stable


stages:
    - build
    
docker:build:Qt:5.9:
    stage: build
    script:
        - docker build .
        
docker:build:Qt:5.8:
    stage: build
    script:
        - docker build . -f 'Qt[5.8]-Android-Dockerfile'
